tools:
  - type: "function"
    function:
      name: "search"
      description: "Searches the web for a given query using the Tavily API."
      parameters:
        query:
          type: "string"
          description: "The search query."
  - type: "function"
    function:
      name: "read_file"
      description: "Reads the content of a file from the current working directory."
      parameters:
        filename:
          type: "string"
          description: "The name of the file to read."
  - type: "function"
    function:
      name: "write_file"
      description: "Writes content to a file in the current working directory."
      parameters:
        filename:
          type: "string"
          description: "The name of the file to write to."
        content:
          type: "string"
          description: "The content to write to the file."
  - type: "function"
    function:
      name: "save_to_memory"
      description: "Saves a document to the vector store."
      parameters:
        document:
          type: "string"
          description: "The document to save."
        metadata:
          type: "object"
          description: "The metadata for the document."
  - type: "function"
    function:
      name: "retriever"
      description: "Retrieves information from the vector store."
      parameters:
        query:
          type: "string"
          description: "The query to search for."
