
tools:
  - name: "search"
    description: "Searches the web for a given query using the Tavily API."
    type: "function"
    handler: "search"
    requires_approval: false
    config:
      params:
        - name: "query"
          type: "string"
          required: true

  - name: "read_file"
    description: "Reads the content of a file from the current working directory."
    type: "cli"
    handler: "cli_handler"
    requires_approval: true
    config:
      command: ["cat"]
      params:
        - name: "filename"
          type: "filepath"
          required: true

  - name: "write_file"
    description: "Writes content to a file in the current working directory."
    type: "cli"
    handler: "cli_handler"
    requires_approval: true
    config:
      command: ["tee"]
      params:
        - name: "filename"
          type: "filepath"
          required: true
        - name: "content"
          type: "string"
          required: true
