def planner(state):
    # For now, we'll hardcode a tool call.
    # Later, this will be generated by an LLM.
    tool_call = {
        "tool": "read_file",
        "params": {"filename": "test.txt"}
    }
    return {"messages": [tool_call]}