def planner(state):
    # For now, we'll hardcode a sequence of tool calls.
    # Later, this will be generated by an LLM.
    if len(state["messages"]) == 1:
        tool_call = {
            "tool": "save_to_memory",
            "params": {"document": "Jules is a software engineer."}
        }
    else:
        tool_call = {
            "tool": "retriever",
            "params": {"query": "who is Jules"}
        }
    return {"messages": [tool_call]}